# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
   include:
     - master
  paths:
    include:
      - ARMTemplates/template.json

variables:
  # Resouce Group Name
  rgName: 'cm-armdeploytest1'
  locName: 'Japan East'

  # Working Directory
  workingDirectory: '$(System.DefaultWorkingDirectory)/ARMTemplates'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Edtter (bd5c9737-10a5-4178-9b83-fd223f7b4bb4)'
    subscriptionId: 'bd5c9737-10a5-4178-9b83-fd223f7b4bb4'
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(rgName)
    location: $(locName)
    templateLocation: 'Linked artifact'
    csmFile: 'ARMTemplates/template.json'
    csmParametersFile: 'ARMTemplates/parameters.json'
    deploymentMode: 'Incremental'
    deploymentName: 'cm-arm-deployment'
    deploymentOutputs: 'cm-arm-deployment-outputs'
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
