# Sample workflow for Azure Static Web Apps
name: Sample for Azure Static Web Apps CI/CD

on: 
  workflow_dispatch:
#   push:
#     branches:
#       - master
#     paths:
#       - 'CongestionStaticWebVueApp/**'
#       - '.github/workflows/**'
#   pull_request:
#     types: [opened, synchronize, reopened, closed]
#     branches:
#       - master
#     paths:
#       - 'CongestionStaticWebVueApp/**'
#       - '.github/workflows/**'

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_SKY_0EFF05900 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "CongestionStaticWebVueApp" # App source code path
          api_location: "CongestionStaticWebVueApp/api" # Api source code path - optional
          app_artifact_location: "dist" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_SKY_0EFF05900 }}
          action: "close"
